version: "3.9"
services:
  rabbitmq-backoff:
    image: rabbitmq:3.8.22-management-alpine
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest